package com.example.agritrader.navigation

const val ROUTE_ABOUT = "about"
const val ROUTE_HOME = "home"
const val ROUTE_PHOME = "phome"
const val ROUTE_HOME2 = "home2"
const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_ADD_PRODUCT = "add_product"
const val ROUTE_UPDATE_PRODUCT = "update_product"
const val ROUTE_VIEW_PRODUCT = "view_product"
const val ROUTE_VIEW_PRODUCT2 = "view_product2"
const val ROUTE_VIEW_UPLOAD = "view_upload"
const val ROUTE_VIEW_UPLOADS = "view_uploads"
const val ROUTE_REGISTER2 = "register2"
const val ROUTE_LOGIN2 = "login2"